import type { Metadata } from 'next';
import './globals.css';
import { Inter, Geist_Mono } from 'next/font/google';
import { cn } from '@/lib/utils';
import { AnchoredToastProvider, ToastProvider } from '@/components/ui/toast';

const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-mono' });

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        inter.variable,
        geistMono.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <ToastProvider>
          <AnchoredToastProvider>{children}</AnchoredToastProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
