import type { Metadata } from 'next';
import './globals.css';
import { Inter, Geist_Mono } from 'next/font/google';
import { cn } from '@/lib/utils';
import { AnchoredToastProvider, ToastProvider } from '@/components/ui/toast';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { TooltipProvider } from '@/components/ui/tooltip';

const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-mono' });

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        inter.variable,
        geistMono.variable,
      )}
    >
      <body
        className="antialiased selection:bg-emerald-200 selection:text-emerald-900 dark:selection:bg-emerald-800/50 dark:selection:text-emerald-50"
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ToastProvider>
            <TooltipProvider>
              <AnchoredToastProvider>{children}</AnchoredToastProvider>
            </TooltipProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
